openapi: 3.0.0
info:
  contact:
    email: support@datadoghq.com
    name: Datadog Support
    url: https://www.datadoghq.com/support/
  description: The Datadog API is an HTTP REST API. The API uses resource-oriented URLs to call the API, uses status codes to indicate the success or failure of requests, returns JSON from all requests, and uses standard HTTP response codes. Use the Datadog API to access the Datadog platform programmatically.
  title: Datadog Account Upload API
  version: '1.0'
servers:
- url: https://{subdomain}.{site}
  variables:
    site:
      default: datadoghq.com
      description: The regional site for Datadog customers.
      enum:
      - datadoghq.com
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ap1.datadoghq.com
      - datadoghq.eu
      - ddog-gov.com
    subdomain:
      default: api
      description: The subdomain where the API is deployed.
- url: '{protocol}://{name}'
  variables:
    name:
      default: api.datadoghq.com
      description: Full site DNS name.
    protocol:
      default: https
      description: The protocol for accessing the API.
- url: https://{subdomain}.{site}
  variables:
    site:
      default: datadoghq.com
      description: Any Datadog deployment.
    subdomain:
      default: api
      description: The subdomain where the API is deployed.
security:
- apiKeyAuth: []
  appKeyAuth: []
tags:
- name: Upload
paths:
  /api/v2/cost/custom_costs:
    put:
      description: Upload a Custom Costs file.
      operationId: UploadCustomCostsFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomCostsFileUploadRequest'
        required: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomCostsFileUploadResponse'
          description: Accepted
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Forbidden
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      security:
      - apiKeyAuth: []
        appKeyAuth: []
      - AuthZ:
        - cloud_cost_management_write
      summary: Datadog Upload Custom Costs File
      tags:
      - Upload
      x-menu-order: 11
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /api/v2/saml_configurations/idp_metadata:
    post:
      description: 'Endpoint for uploading IdP metadata for SAML setup.


        Use this endpoint to upload or replace IdP metadata for SAML login configuration.'
      operationId: UploadIdPMetadata
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/IdPMetadataFormData'
        required: true
      responses:
        '200':
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
          description: Forbidden
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
      summary: Datadog Upload Idp Metadata
      tags:
      - Upload
      x-codegen-request-body-name: body
      x-menu-order: 1
      x-permission:
        operator: OR
        permissions:
        - org_management
      x-undo:
        type: idempotent
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    CustomCostsFileMetadata:
      description: Schema of a Custom Costs metadata.
      properties:
        billed_cost:
          description: Total cost in the cost file.
          example: 100.5
          format: double
          type: number
        billing_currency:
          description: Currency used in the Custom Costs file.
          example: USD
          type: string
        charge_period:
          $ref: '#/components/schemas/CustomCostsFileUsageChargePeriod'
        name:
          description: Name of the Custom Costs file.
          example: my_file.json
          type: string
        provider_names:
          description: Providers contained in the Custom Costs file.
          items:
            description: Name of the provider.
            example: my_provider
            type: string
          type: array
        status:
          description: Status of the Custom Costs file.
          example: active
          type: string
        uploaded_at:
          description: Timestamp, in millisecond, of the upload time of the Custom Costs file.
          example: 1704067200000
          format: double
          type: number
        uploaded_by:
          $ref: '#/components/schemas/CustomCostsUser'
      type: object
    APIErrorResponse:
      description: API error response.
      properties:
        errors:
          description: A list of errors.
          example:
          - Bad Request
          items:
            description: A list of items.
            example: Bad Request
            type: string
          type: array
      required:
      - errors
      type: object
    IdPMetadataFormData:
      description: The form data submitted to upload IdP metadata
      properties:
        idp_file:
          description: The IdP metadata XML file
          format: binary
          type: string
          x-mimetype: application/xml
          example: abc-123-def
      type: object
    CustomCostsFileUploadRequest:
      description: Request for uploading a Custom Costs file.
      items:
        $ref: '#/components/schemas/CustomCostsFileLineItem'
      type: array
    CustomCostsFileUsageChargePeriod:
      description: Usage charge period of a Custom Costs file.
      properties:
        end:
          description: End of the usage of the Custom Costs file.
          example: 1706745600000
          format: double
          type: number
        start:
          description: Start of the usage of the Custom Costs file.
          example: 1704067200000
          format: double
          type: number
      type: object
    CustomCostUploadResponseMeta:
      description: Meta for the response from the Upload Custom Costs endpoints.
      properties:
        version:
          description: Version of Custom Costs file
          type: string
          example: example_value
      type: object
    CustomCostsFileLineItem:
      description: Line item details from a Custom Costs file.
      properties:
        BilledCost:
          description: Total cost in the cost file.
          example: 100.5
          format: double
          type: number
        BillingCurrency:
          description: Currency used in the Custom Costs file.
          example: USD
          type: string
        ChargeDescription:
          description: Description for the line item cost.
          example: Monthly usage charge for my service
          type: string
        ChargePeriodEnd:
          description: End date of the usage charge.
          example: '2023-02-28'
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
        ChargePeriodStart:
          description: Start date of the usage charge.
          example: '2023-02-01'
          pattern: ^\d{4}-\d{2}-\d{2}$
          type: string
        ProviderName:
          description: Name of the provider for the line item.
          type: string
          example: abc-123-def
        Tags:
          additionalProperties:
            type: string
          description: Additional tags for the line item.
          type: object
      type: object
    CustomCostsFileUploadResponse:
      description: Response for Uploaded Custom Costs files.
      properties:
        data:
          $ref: '#/components/schemas/CustomCostsFileMetadataHighLevel'
        meta:
          $ref: '#/components/schemas/CustomCostUploadResponseMeta'
      type: object
    CustomCostsFileMetadataHighLevel:
      description: JSON API format for a Custom Costs file.
      properties:
        attributes:
          $ref: '#/components/schemas/CustomCostsFileMetadata'
        id:
          description: ID of the Custom Costs metadata.
          type: string
          example: abc-123-def
        type:
          description: Type of the Custom Costs file metadata.
          type: string
          example: metric alert
      type: object
    CustomCostsUser:
      description: Metadata of the user that has uploaded the Custom Costs file.
      properties:
        email:
          description: The name of the Custom Costs file.
          example: email.test@datadohq.com
          type: string
        icon:
          description: The name of the Custom Costs file.
          example: icon.png
          type: string
        name:
          description: Name of the user.
          example: Test User
          type: string
      type: object
  responses:
    TooManyRequestsResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIErrorResponse'
      description: Too many requests
  securitySchemes:
    AuthZ:
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/v1/authorize
          scopes:
            apm_api_catalog_read: View API catalog and API definitions.
            apm_api_catalog_write: Add, modify, and delete API catalog definitions.
            apm_read: Read and query APM and Trace Analytics.
            apm_service_catalog_read: View service catalog and service definitions.
            apm_service_catalog_write: Add, modify, and delete service catalog definitions when those definitions are maintained by Datadog.
            appsec_vm_read: View infrastructure, application code, and library vulnerabilities. This does not restrict API or inventory SQL access to the vulnerability data source.
            cases_read: View Cases.
            cases_write: Create and update cases.
            ci_visibility_pipelines_write: Create CI Visibility pipeline spans using the API.
            ci_visibility_read: View CI Visibility.
            cloud_cost_management_read: View Cloud Cost pages and the cloud cost data source in dashboards and notebooks. For more details, see the Cloud Cost Management docs.
            cloud_cost_management_write: Configure cloud cost accounts and global customizations. For more details, see the Cloud Cost Management docs.
            code_analysis_read: View Code Analysis.
            continuous_profiler_pgo_read: Read and query Continuous Profiler data for Profile-Guided Optimization (PGO).
            create_webhooks: Create webhooks integrations.
            dashboards_embed_share: Create, modify, and delete shared dashboards with share type 'embed'.
            dashboards_invite_share: Create, modify, and delete shared dashboards with share type 'invite'.
            dashboards_public_share: Generate public and authenticated links to share dashboards or embeddable graphs externally.
            dashboards_read: View dashboards.
            dashboards_write: Create and change dashboards.
            data_scanner_read: View Data Scanner configurations.
            data_scanner_write: Edit Data Scanner configurations.
            embeddable_graphs_share: Generate public links to share embeddable graphs externally.
            events_read: Read Events data.
            hosts_read: List hosts and their attributes.
            incident_notification_settings_write: Configure Incidents Notification settings.
            incident_read: View incidents in Datadog.
            incident_settings_write: Configure Incident Settings.
            incident_write: Create, view, and manage incidents in Datadog.
            metrics_read: View custom metrics.
            monitor_config_policy_write: Edit and delete monitor configuration.
            monitors_downtime: Set downtimes to suppress alerts from any monitor in an organization. Mute and unmute monitors. The ability to write monitors is not required to set downtimes.
            monitors_read: View monitors.
            monitors_write: Edit, delete, and resolve individual monitors.
            org_management: Edit org configurations, including authentication and certain security preferences such as configuring SAML, renaming an org, configuring allowed login methods, creating child orgs, subscribing & unsubscribing from apps in the marketplace, and enabling & disabling Remote Configuration for the entire organization.
            security_comments_read: Read comments of vulnerabilities.
            security_monitoring_filters_read: Read Security Filters.
            security_monitoring_filters_write: Create, edit, and delete Security Filters.
            security_monitoring_findings_read: View a list of findings that include both misconfigurations and identity risks.
            security_monitoring_notification_profiles_read: View Rule Security Notification rules.
            security_monitoring_notification_profiles_write: Create, edit, and delete Security Notification rules.
            security_monitoring_rules_read: Read Detection Rules.
            security_monitoring_rules_write: Create and edit Detection Rules.
            security_monitoring_signals_read: View Security Signals.
            security_monitoring_suppressions_read: Read Rule Suppressions.
            security_monitoring_suppressions_write: Write Rule Suppressions.
            security_pipelines_read: View Security Pipelines.
            security_pipelines_write: Create, edit, and delete CSM Security Pipelines.
            slos_corrections: Apply, edit, and delete SLO status corrections. A user with this permission can make status corrections, even if they do not have permission to edit those SLOs.
            slos_read: View SLOs and status corrections.
            slos_write: Create, edit, and delete SLOs.
            synthetics_global_variable_read: View, search, and use Synthetics global variables.
            synthetics_global_variable_write: Create, edit, and delete global variables for Synthetics.
            synthetics_private_location_read: View, search, and use Synthetics private locations.
            synthetics_private_location_write: Create and delete private locations in addition to having access to the associated installation guidelines.
            synthetics_read: List and view configured Synthetic tests and test results.
            synthetics_write: Create, edit, and delete Synthetic tests.
            teams_manage: Manage Teams. Create, delete, rename, and edit metadata of all Teams. To control Team membership across all Teams, use the User Access Manage permission.
            teams_read: Read Teams data. A User with this permission can view Team names, metadata, and which Users are on each Team.
            test_optimization_read: View Test Optimization.
            timeseries_query: Query Timeseries data.
            usage_read: View your organization's usage and usage attribution.
            user_access_invite: Invite other users to your organization.
            user_access_manage: Disable users, manage user roles, manage SAML-to-role mappings, and configure logs restriction queries.
            user_access_read: View users and their roles and settings.
            workflows_read: View workflows.
            workflows_run: Run workflows.
            workflows_write: Create, edit, and delete workflows.
          tokenUrl: /oauth2/v1/token
      type: oauth2
    apiKeyAuth:
      description: Your Datadog API Key.
      in: header
      name: DD-API-KEY
      type: apiKey
      x-env-name: DD_API_KEY
    appKeyAuth:
      description: Your Datadog APP Key.
      in: header
      name: DD-APPLICATION-KEY
      type: apiKey
      x-env-name: DD_APP_KEY
    bearerAuth:
      scheme: bearer
      type: http
      x-env-name: DD_BEARER_TOKEN
x-group-parameters: true
x-merge-override:
  paths: false
